### PR TITLE
adding pre_ping to sqlalchemy create_engine option

### PR DESCRIPTION
**Pull request by epifanio**
This option should mitigate a problem arising when running GeoHealthCheck in a docker swarm environment with a PostgreSQL database backend.

### CODE REVIEW

**Review by justb4 — CHANGES_REQUESTED** [review]
Although this fix will work in the Swarm case, it will add a small overhead to each and every DB-call as 'under the hood' SQLAlchemy will issue a `SELECT 1` before the actual DB call. 
So I would rather see this as a configurable option, with a default of `False`. At this moment it is hard to assess the overhead. Anyone has figures? @tomkralidis or @fsteggink ? If the overhead is like under 1% we may hardcode it to `True`. 
Still I would also like the `SQLALCHEMY_ENGINE_OPTIONS` structure in `config_main.py`.
If we go for a parameter we could call it `SQLALCHEMY_ENGINE_OPTION_PRE_PING`, set it during config initialization. Then it can also be documented.

There is a build error from the codestyle checker `flake8`. Nothing serious:
```
./GeoHealthCheck/init.py:87:80: E501 line too long (83 > 79 characters)
Error: Process completed with exit code 1.
```

**Comment by epifanio** [comment]
will work something like:

Adding:

```python
SQLALCHEMY_ENGINE_OPTION_PRE_PING = False
```
in [config_main.py](https://github.com/geopython/GeoHealthCheck/blob/master/GeoHealthCheck/config_main.py)

and then change [init.py](https://github.com/geopython/GeoHealthCheck/blob/master/GeoHealthCheck/init.py) to:

```python
        SQLALCHEMY_ENGINE_OPTIONS = {
                                 'pool_pre_ping': app.config['SQLALCHEMY_ENGINE_OPTION_PRE_PING']
                                 }
        App.db_instance = SQLAlchemy(app, 
                                     engine_options=SQLALCHEMY_ENGINE_OPTIONS)
```

**Review by justb4 — CHANGES_REQUESTED** [review]
When adding a new config variable the following three changes are required as well (yes, a bit elaborate, and duplicated), This has to do with the ability to use (e.g. Docker, Kubernetes) environment vars over `config.py` files that was added later in the project.

* the [Dockerfile](https://github.com/geopython/GeoHealthCheck/blob/master/Dockerfile) with default value
* [Docker default config](https://github.com/geopython/GeoHealthCheck/blob/master/docker/config_site.py)
* [Documentation entry](https://github.com/geopython/GeoHealthCheck/blob/master/docs/config.rst).

**Review by justb4 — CHANGES_REQUESTED** [review]
See my comment on `docker/config_site.py` file.

**Comment by fsteggink** [comment]
> Although this fix will work in the Swarm case, it will add a small overhead to each and every DB-call as 'under the hood' SQLAlchemy will issue a `SELECT 1` before the actual DB call. So I would rather see this as a configurable option, with a default of `False`. At this moment it is hard to assess the overhead. Anyone has figures? @tomkralidis or @fsteggink ? If the overhead is like under 1% we may hardcode it to `True`. Still I would also like the `SQLALCHEMY_ENGINE_OPTIONS` structure in `config_main.py`. If we go for a parameter we could call it `SQLALCHEMY_ENGINE_OPTION_PRE_PING`, set it during config initialization. Then it can also be documented.

I'd like to have this as a configurable option. GHC can already be quite heavy on the DB (as I've encountered), so if extra overhead can be avoided, that would be definitely my preference.

**Comment by epifanio** [comment]
> I'd like to have this as a configurable option. GHC can already be quite heavy on the DB (as I've encountered), so if extra overhead can be avoided, that would be definitely my preference.

The revised PR implements the `SQLALCHEMY_ENGINE_OPTION_PRE_PING` as configurable options, by default set to `FALSE`.

**Review by justb4 — APPROVED** [review]
Ok, all good to go.

**Comment by justb4** [comment]
Sorry there is still a slight coding convention error:
```
Run flake8
./GeoHealthCheck/init.py:87:80: E501 line too long (97 > 79 characters)
./GeoHealthCheck/init.py:89:42: W291 trailing whitespace
```
Please always run `flake8` before committing.
pip install flake8 and run `flake8` at root of project.

**Review by justb4 — APPROVED** [review]
Ok, looks good now!

**Comment by justb4** [comment]
Don't mind the failing tests, has to do with remote endpoints.

**Pull request merged**
