### PR TITLE
Add global probe timeout configuration

### PR DESCRIPTION
**Pull request by mkofahl**
According to http://docs.python-requests.org/en/master/user/quickstart/#timeouts, there is no default timeout for the requests object. So a single webservice may stop GHC working. This PR adds the global configuration GHC_RUN_PROBE_TIMEOUT used for probes.

Consider adding a timeout for web norifications.

### CODE REVIEW

**Comment by justb4** [comment]
Good suggestion! Is a problem in practice. Some changes we would like:

* name the config `GHC_PROBE_HTTP_TIMEOUT_SECS`: then it also clear that these are seconds (like other config names e.g. `GHC_RETENTION_DAYS` and `GHC_METADATA_CACHE_SECS`. Plus a `Probe` may perform multiple HTTP requests (see e.g. `wmsdrilldown.py`), so it is really the timeout per HTTP request within a `Probe Run`, not for the `Probe` itself.
* update the [Documentation](https://github.com/geopython/GeoHealthCheck/blob/master/docs/config.rst)
* update the [Dockerfile](https://github.com/geopython/GeoHealthCheck/blob/master/Dockerfile)

Travis error can be fixed by running `flake8` tool in root and fix Python formatting.

**Comment by mkofahl** [comment]
@justb4 done

**Comment by justb4** [comment]
Thanks again @mkofahl. Give us some time before merge, as today I have workshop and give GHC presentation.

**Comment by justb4** [comment]
@mkofahl Sorry for the delay and thanks again!

**Pull request merged**
