### PR TITLE
resource authentication

### PR DESCRIPTION
**Pull request by mkofahl**
HTTP Basic username/password implementation (issue #9). Credentials are stored per-probe, not üer-ressource. This allows to test the ressource and proper function of the security middleware at the same time.

### CODE REVIEW

**Comment by mkofahl** [comment]
not sure whether I can safely modify the tests.

**Comment by justb4** [comment]
@mkofahl can you expand why auth per Probe is added i.s.o. auth per Resource? Probes in general will always perform HTTP request(s) on the same Resource URL.

**Comment by mkofahl** [comment]
@justb4 I agree that authentication per resource may be sufficient in most cases. But having it per probe may allow to perform the following tests on access-protected resources:
- test that Capabilities are public: a GetCaps probe without credentials
- test security middleware: expect 401/403 for GetFeature/GetMap without credentials
- test invalid credentials: expect 401/403 (check currently not implemented)
- test spatial obligation: e.g. GetFeature for user1 shall contain string xyz but has to be empty or fail for valid user2
- test attribute filtering: e.g. GetFeature for user1 shall contain string xyz but another string for valid user2

There may be more scenarios. I think it's valid to say a resource is working properly in all only if the security middleware does it's job, too. That's why I implemented the authentication per-probe and not per-resource.

**Comment by justb4** [comment]
Thanks for clarification. These scenario's are actually to be used in production? Quite advanced!
In any case, we will hold-off this PR for now for the following reasons:

* we would rather first see auth-per-Resource implemented as per the long-standing issue #9 . That issue also appears to be more involved than just adding basic auth (many more forms of auth). We can learn from that implementation. 
* the "Probe-form-space" will always show these new auth params while not used in most cases
* every new `Probe` needs to be aware of the `Merge Params` stuff
* we need to make sure that auth info is somehow not visible for others than Resource owner and admin users

What I was thinking that may help to implement your scenarios: issue #186 (allow setting per-Probe request headers) implemented as general Probe feature. In fact multiple auth methods may be implemented with #186, like e.g. Bearer Token.

So all in all I think that we can progress for the benefit of most GHC users by implementing #9 and #186 first and then review this PR #190 again.

**Comment by mkofahl** [comment]
Sounds reasonable having a common auth field per resource and something more flexible per probe.

**Comment by justb4** [comment]
@mkofahl yes, let's do that. Thanks for thinking along!

**Comment by justb4** [comment]
@mkofahl As this PR has been resolved by PR #259 I propose to close this PR.

**Comment by justb4** [comment]
As this PR and issue #9 have been resolved by PR #259 I  close this PR.

**Pull request closed without merging**
