### PR TITLE
add option to disable a resource (#161)

### PR DESCRIPTION
**Pull request by tomkralidis**
Implements #161.

@justb4 I wasn't able to create the alembic migrations (as per https://github.com/geopython/GeoHealthCheck/tree/master/GeoHealthCheck/migrations/README.md):

```bash
(GeoHealthCheck)tkralidi@www:~/work/foss4g/GeoHealthCheck/GeoHealthCheck/GeoHealthCheck$ python manage.py db migrate
init.py: created GHC App instance
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
Traceback (most recent call last):
  File "manage.py", line 53, in <module>
    manager.run()
  File "/home/tkralidi/work/foss4g/GeoHealthCheck/local/lib/python2.7/site-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/home/tkralidi/work/foss4g/GeoHealthCheck/local/lib/python2.7/site-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/home/tkralidi/work/foss4g/GeoHealthCheck/local/lib/python2.7/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/home/tkralidi/work/foss4g/GeoHealthCheck/local/lib/python2.7/site-packages/flask_migrate/__init__.py", line 182, in migrate
    version_path=version_path, rev_id=rev_id)
  File "/home/tkralidi/work/foss4g/GeoHealthCheck/local/lib/python2.7/site-packages/alembic/command.py", line 176, in revision
    script_directory.run_env()
  File "/home/tkralidi/work/foss4g/GeoHealthCheck/local/lib/python2.7/site-packages/alembic/script/base.py", line 425, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/home/tkralidi/work/foss4g/GeoHealthCheck/local/lib/python2.7/site-packages/alembic/util/pyfiles.py", line 93, in load_python_file
    module = load_module_py(module_id, path)
  File "/home/tkralidi/work/foss4g/GeoHealthCheck/local/lib/python2.7/site-packages/alembic/util/compat.py", line 75, in load_module_py
    mod = imp.load_source(module_id, path, fp)
  File "migrations/env.py", line 87, in <module>
    run_migrations_online()
  File "migrations/env.py", line 80, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/home/tkralidi/work/foss4g/GeoHealthCheck/local/lib/python2.7/site-packages/alembic/runtime/environment.py", line 836, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/home/tkralidi/work/foss4g/GeoHealthCheck/local/lib/python2.7/site-packages/alembic/runtime/migration.py", line 321, in run_migrations
    for step in self._migrations_fn(heads, self):
  File "/home/tkralidi/work/foss4g/GeoHealthCheck/local/lib/python2.7/site-packages/alembic/command.py", line 156, in retrieve_migrations
    revision_context.run_autogenerate(rev, context)
  File "/home/tkralidi/work/foss4g/GeoHealthCheck/local/lib/python2.7/site-packages/alembic/autogenerate/api.py", line 415, in run_autogenerate
    self._run_environment(rev, migration_context, True)
  File "/home/tkralidi/work/foss4g/GeoHealthCheck/local/lib/python2.7/site-packages/alembic/autogenerate/api.py", line 427, in _run_environment
    raise util.CommandError("Target database is not up to date.")
alembic.util.exc.CommandError: Target database is not up to date.
```

### CODE REVIEW

**Comment by justb4** [comment]
@tomkralidis in this case you have to create a migration. The steps depend on the initial state of your DB. Alembic keeps track of current schema version via the table `alembic_version`. If this table does not exist, then on `python manage.py db migrate` you get the above error. So I assume that is in your case. https://flask-migrate.readthedocs.io/en/latest/

Make your DB uptodate with previous (before `active` was added, but you can leave the `active` column def in `models.py`) first:

```
python manage.py db upgrade (or paver upgrade)
```

You now should have the table `alembic_version`. Now create the migration:

```
python manage.py db migrate
```
This will create a new (third) version file under `migrations/versions/<randomhex>/py`. This file needs to be hand-adapted for the `upgrade()` and `downgrade()` functions.  Somehow Alembic does not detect the column addition (in my case, PostGIS).

I tried, but ran into second problem: the column is not `Nullable` and `Default` values are not filled in automatically. See https://coderwall.com/p/8zw7bq/modifying-nullable-columns-in-alembic. Finally  this code which worked for me (your revision Id will be different I think).

```
"""empty message

Revision ID: f17ae1f9a0be
Revises: 992013af402f
Create Date: 2017-09-08 12:24:18.038337

"""
from alembic import op
import sqlalchemy as sa
import imp
import os


# revision identifiers, used by Alembic.
revision = 'f17ae1f9a0be'
down_revision = '992013af402f'
branch_labels = None
depends_on = None

alembic_helpers = imp.load_source('alembic_helpers', (
    os.getcwd() + '/' + op.get_context().script.dir + '/alembic_helpers.py'))

def upgrade():
    if not alembic_helpers.table_has_column('resource', 'active'):
        from sqlalchemy.sql import table, column
        print('Column active not present in resource table, will create')
        op.add_column(u'resource', sa.Column('active', sa.Boolean, nullable=True, default=True))
        resource = table('resource', column('active'))
        op.execute(resource.update().values(active=True))
        op.alter_column('resource', 'active', nullable=False)
    else:
        print('Column active already present in resource table')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    print('Dropping Column active from resource table')
    op.drop_column(u'resource', 'active')
```

So adds column first, with `nullable=True`, then fills existing records with `True`, then `alters` column to set `nullable=False`. You may also want to test the downgrade. 
It is a bit tricky, but finally Alembic solves what is usually a very hard problem.
We will need to adapt the README.

**Comment by tomkralidis** [comment]
Thanks @justb4.  Added.

**Comment by tomkralidis** [comment]
Closed in lieu of #163

**Comment by justb4** [comment]
Hmm, I get a 500 on demo and cannot login on dev...

**Comment by tomkralidis** [comment]
try demo again? For dev, I accidentally wiped out the db, so I copied db from demo.

**Comment by justb4** [comment]
ok, only on dev get internal server error when adding or editing  a resource. DB permission issue?

**Comment by justb4** [comment]
```
Save: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (sqlite3.OperationalError) attempt to write a readonly database [SQL: u'UPDATE resource SET active=? WHERE resource.identifier = ?'] [parameters: (0, 31)]  
```

**Comment by tomkralidis** [comment]
Try again?

**Comment by justb4** [comment]
Ok now, thanks!

**Pull request merged**
