### PR TITLE
Dockerization of GHC

### PR DESCRIPTION
**Pull request by yjacolin**
@tomkralidis Do not merge now, this is just for get your comments :) you can test it with:
```
docker run -d --name GeoHealtCheck -p 8082:80 yjacolin/geohealthcheck 
```

ping @fvanderbiest

### CODE REVIEW

**Comment by hannesaddec** [comment]
Does docker accepts cron jobs that way ?


Mit TouchDown von meinem Android-Telefon gesendet (www.symantec.com)

-----Original Message-----

**Comment by yjacolin** [comment]
no cron job are not enabled at this moment. We need another container specific for this like http://dshearer.github.io/jobber/

**Comment by rduivenvoorde** [comment]
@yjacolin thought to give it a try?

selection_052

anything else I should do before starting it?

**Comment by yjacolin** [comment]
The docker is currently not working. I have a python issue somewhere in the docker. Probably the same as you but I can't figure out where it come from.

I also need to create a docker for the cron job.

**Comment by yjacolin** [comment]
@rduivenvoorde good news, I will updated my PR.

**Comment by yjacolin** [comment]
We need #53 to make this PR work correctly.

**Comment by yjacolin** [comment]
@hannesaddec @rduivenvoorde @tomkralidis This PR is finished. We should wait for #53 to bne merged to have a fully docker infra for GHC.

**Comment by tomkralidis** [comment]
Thanks @yjacolin for this contribution!

**Comment by tomkralidis** [comment]
@yjacolin I'm running into issues making Docker GHC work.  See discussion in https://gitter.im/geopython/GeoHealthCheck

**Pull request merged**
