### PR TITLE
Issue 221 wfs3 Probe: OpenAPI spec validator for /api endpoint

### PR DESCRIPTION
**Pull request by justb4**
This PR adds an OpenAPI Validator that checks the OpenAPI spec file returned by the WFS3 `/api` endpoint.
The Probe is relatively simple as all work is done by: https://github.com/p1c2u/openapi-spec-validator.

### CODE REVIEW

**Comment by tomkralidis** [comment]
Thanks @justb4.  What's the impact of adding an OpenAPI document validator to GHC (for example, in parallel, do we validate Capabilities XML for current OGC standards)?  In addition, is the validator authoritative? Is there something we can leverage from SwaggerHub?

**Comment by justb4** [comment]
@tomkralidis see discussion here: https://github.com/geopython/pygeoapi/issues/168 
I think an OpenAPI validator is very useful, though indeed it must be authoritative. Also the Probe itself is optional to use (it is specific to (the `/api` endpoint of WFS3/Features now), but I could imagine a generic version for any OAS endpoint `WWW:Link` `Resource type`, possibly even versioned. btw only the `ldproxy` endpoints do currently validate (but they have no `Processes`) all other WFS3 endpoints do not validate. 

For GetCapabilities GHC runs several validations as `Checks`: like XML parsing and certain keywords, but not yet schema-validation, but that could be an additional `Check`.

**Comment by tomkralidis** [comment]
Fair enough. +1 as an optional check. Having said this, once we figure out the OGC short names for the new generation of specs, we should be using those (`OGC-API-Features:1.0`) which ties to the root URL of the WFS3, as opposed to registering an OpenAPI document to GHC.

**Comment by justb4** [comment]
I take this that we can merge? "Optional" here means: one can choose to (not) use the new `WFS3OpenAPIValidator`. The default Probe (assigned when WFS3 Resource added) remains the `WFS3Drilldown` Probe with `basic` checks.

**Pull request merged**
