### PR TITLE
py3k deps update

### PR DESCRIPTION
**Pull request by tomkralidis**

### CODE REVIEW

**Comment by tomkralidis** [comment]
@justb4 the changes are to safeguard and work for both Python 2 and 3.  Having said this, moving to Python 3 as the default is a good idea.  I'll try that, as well as fix some test problems.

**Comment by justb4** [comment]
Hmm, I begin to realize that moving to Python3 and supporting also 2.7 can have quite a few issues. For example: https://stackoverflow.com/questions/11914472/stringio-in-python3 but also the Probe Plugin system does quite some intricate reflection stuff (i.e. creating Objects from strings), that  may not work in Py3.

Also (see our personal Gitter conversation, you may have missed my msg from sept 18) I would rather first bring out 0.4.0 version as the master branch is now stable for some time. See my proposal in Gitter. So I propose this order:

- bring out v0.4.0
- move the test servers to uptodate Ubuntu/python servers using Docker deployment 
- merge in the branch ["per resource scheduling"](https://github.com/geopython/GeoHealthCheck/tree/per_resource_scheduling) I have been working on since the code sprint and is used in various deployments by me
- support Python3 via the `dev` branch

Sorry, my initial reaction was "go" but then I realized the other stuff waiting and implications.

**Comment by tomkralidis** [comment]
@justb4 +1/agree, let's get 0.4.0 out of the way as the first step.

**Comment by justb4** [comment]
@tomkralidis Yes 0.4.0 first. Then I propose to merge in this branch to master: https://github.com/geopython/GeoHealthCheck/tree/per_resource_scheduling . 
Kept that branch even with master. 
And then outstanding fixes+py3. I have more time to work on GHC coming 2 months.

**Comment by justb4** [comment]
We need to do this at some point. But like many projects as Django (2.0 is PY3 only) etc. I would prefer not to have simultaneous Py2 and Py3 support, given that:

* Py2 will be EOL very soon (less than a year)
* maintenance: we already have limited human resources
* many users (more and more) deploying with Docker

Like [with Stetl in a similar PR](https://github.com/geopython/stetl/pull/81) we decided to:

* bring out one last Py2 release (and Docker Image)
* make branch of that release, for urgent fixes only
* bring out fresh Py3-only version

**Comment by tomkralidis** [comment]
Closing in lieu of #280

**Pull request closed without merging**
