### PR TITLE
add jspark locally

### PR DESCRIPTION
**Pull request by tomkralidis**

### CODE REVIEW

**Comment by tomkralidis** [comment]
FYI CI failures are unrelated and likely due to Python 3.7 support.  @justb4 perhaps we should update to Python 3.8+ (in another PR)?

**Comment by justb4** [comment]
CI failures are flake8 deps related it looks like: https://github.com/PyCQA/flake8/issues/1701

You may try

```
flake8==5.0.4
Paver==1.3.4
pylint==2.13.9
```
in `requirements-dev.txt`. Cannot reproduce locally.

**Comment by tomkralidis** [comment]
Looks like a different unrelated CI error.

**Comment by justb4** [comment]
Not really but the Docker Image venv also runs Python 3.7.

**Comment by tomkralidis** [comment]
Suggest we merge this PR and have a future/sprint activity to upgrade to 3.8+?

**Pull request merged**
