### PR TITLE
Include info about needing python dev to build

### PR DESCRIPTION
**Pull request by archaeogeek**
This might need slight rewriting but we need to include python-dev as a requirement or the paver setup bit fails

### CODE REVIEW

**Comment by justb4** [comment]
Not sure what you mean with "python dev libraries". E.g. are you referring to the `python-dev` package in case of Ubuntu?

**Comment by archaeogeek** [comment]
Yes, definitely for ubuntu- do they come built-in for all other operating systems?

**Comment by justb4** [comment]
`python-dev` is the package that contains the header files for the Python C API, which is used by some Python packages like `lxml`. AFAICS for GHC only `psycopg2`, when using Postgres i.s.o. `sqlite` would require header files thus `python-dev`. Or did you found otherwise? 

Using Postgres/`psycopg2` is lacking completely in the documentation I now see...

For other OSs it is very much dependent on how Python is installed. e.g. on Mac OSX using Python from `homebrew` already includes headers.

**Comment by archaeogeek** [comment]
Yes I'm using postgresql. So it looks as if my suggested rewrite needs a bit more work- I'll adjust it.

Jo

**Comment by archaeogeek** [comment]
I've made a change to the way this is phrased- does it work a bit better now?

**Comment by justb4** [comment]
Ok now. Thanks for patience @archaeogeek !

**Pull request merged**
