### PR TITLE
Bugfix: Huge input lookup, for large XML files #361

### PR DESCRIPTION
**Pull request by bart-v**
Simple fix for #361

### CODE REVIEW

**Review by justb4 — CHANGES_REQUESTED** [review]
Thanks for your contribution!

Minor: you've hit the `flake8` verification: line-length should be max 79 chars.

I can see the need, but the solution also has security implications, see:
https://lxml.de/FAQ.html#is-lxml-vulnerable-to-xml-bombs . My preference would be to make this option configurable.

**Comment by bart-v** [comment]
OK, but creating a new configuration option in GHC is out of my comfort zone :)

**Comment by borrob** [comment]
I worked upon your solution and turned the `huge_tree` to a configurable option (in `config_main.py`, the `Dockerfile` and in the environment files). It defaults to False. I've sent a PR to @bart-v at his branch `bart-v:patch-1`. If that merge is accepted, it should pop up here automatically.

**Comment by bart-v** [comment]
Excellent, thanks

**Comment by justb4** [comment]
Thanks @bart-v and @borrob . This is also a test with the new GitHub CI Workflows I just enabled. So see first what they say.

**Review by justb4 — APPROVED** [review]
LGTM, will merge. The failing unit test is some HTTP problem with PDOK. Same tests succeed in Docker workflow.

**Pull request merged**
