### PR TITLE
add about page, font-awesome CDN, project init info

### PR DESCRIPTION
**Pull request by tomkralidis**
Minor doc updates. Note this adds an external network dependency to font-awesome CDN.

### CODE REVIEW

**Comment by justb4** [comment]
Good, only I deliberately avoided external network dependencies to be able to present without a network connection (as sometimes happens at confs), just firing up the local index.html.  So if not really required I would like to leave out font-awesome CDN. Ok, if I remove it?

**Comment by hannesaddec** [comment]
+1

Hannes I. Reuter – EC - DG ESTAT - Unit E4 -Regional statistics and geographical information
Office BECH-A3-049, Rue Alphonse Weicker 5, L-2721 Luxembourg,
Post European Commission, Jean Monnet Building, L-2271 Luxembourg
Phone +352- 4301 -33687 UnitFax +352- 4301-34029
[cid:image001.png@01D2CA4A.0B42BF00]

**Comment by tomkralidis** [comment]
Good point.  Updated to static icons in https://github.com/geopython/GeoHealthCheck/commit/c3f72f0ef62fff360f10d4603a24edf5901b5cf8

**Comment by tomkralidis** [comment]
@hannesaddec please feel free to add an about yourself to the presentation!

**Comment by gisxperts** [comment]
sorry, which presentation ?

**Comment by justb4** [comment]
https://github.com/geopython/GeoHealthCheck/blob/gh-pages/presentation/index.html

**Comment by justb4** [comment]
https://github.com/geopython/GeoHealthCheck/blob/gh-pages/presentation/index.html

Sent by MailWise – See your emails as clean, short chats.

-------- Original Message --------

**Pull request merged**
